### ISSUE TITLE
报错：TypeError: 'NoneType' object has no attribute 'getitem'

### ISSUE THREAD

**Issue by doocii** [Pingze-github/HuabanBatchUpload#1]
运行后报错？求解答，感谢、
Program start
Find 8 images to be uploaded ...
HTTP/GET failed, Now retry ...
HTTP/GET failed, Now retry ...
Successfully load user main page data
Successfully load user board page data
[01:14:31][00] Thread start !
[01:14:31][01] Thread start !
[01:14:31][02] Thread start !
[01:14:31][03] Thread start !
[01:14:31][04] Thread start !
[01:14:31][05] Thread start !
[01:14:31][06] Thread start !
[01:14:31][07] Thread start !

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\admin\Desktop\HuabanBatchUpload-master\lib\batch.py", line 21,
in run
    self.target(self.tname,self.lock,self.args)
  File "C:\Users\admin\Desktop\HuabanBatchUpload-master\lib\batch.py", line 32,
in uploadOne
    upload(file_path,board_name,lock=lock,tname=tname)
  File "C:\Users\admin\Desktop\HuabanBatchUpload-master\lib\upload.py", line 42
 in upload
    file_id = file_data["id"]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by Pingze-github** [comment]
我刚才试了一下，这么长时间过去还是可以用的。
看你这个错误，应该是main里面配置错误，导致上传时被花瓣网拒绝。
可以把你的配置展示一下（打码），看看哪里有问题。

**Comment by doocii** [comment]
# coding=u8
# index.py
# project: HuabanBatchUpload
# author: Pingze-github @ Github

from lib.batch import batchUpload
from lib.auth import getCookies

def main():
    account = "**@qq.com"
    password = "**143"
    cookies_str = getCookies(account,password) # get cookies
    dirpath = "C://Users//admin//Desktop//HuabanBatchUpload-master//test" # dirpath
    board_name = "网页设计" # board name
    batchUpload(cookies_str,dirpath,board_name)

if __name__ == '__main__':
    main()

board_name  我尝试了中文和数字。感谢你的回复

**Comment by Pingze-github** [comment]
更新后，通过微小修改图像文件，突破了花瓣对图片采集的次数限制。
修复中文问题。
